/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoOpCapitalWorkProgramRouteImport } from './routes/co-op-capital-work-program'
import { Route as IndexRouteImport } from './routes/index'

const CoOpCapitalWorkProgramRoute = CoOpCapitalWorkProgramRouteImport.update({
  id: '/co-op-capital-work-program',
  path: '/co-op-capital-work-program',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/co-op-capital-work-program': typeof CoOpCapitalWorkProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/co-op-capital-work-program': typeof CoOpCapitalWorkProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/co-op-capital-work-program': typeof CoOpCapitalWorkProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/co-op-capital-work-program'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/co-op-capital-work-program'
  id: '__root__' | '/' | '/co-op-capital-work-program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoOpCapitalWorkProgramRoute: typeof CoOpCapitalWorkProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/co-op-capital-work-program': {
      id: '/co-op-capital-work-program'
      path: '/co-op-capital-work-program'
      fullPath: '/co-op-capital-work-program'
      preLoaderRoute: typeof CoOpCapitalWorkProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoOpCapitalWorkProgramRoute: CoOpCapitalWorkProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
